name: CICD

on:
  push:
  pull_request:

jobs:
  # -----------------------------
  # client: test + docker
  # -----------------------------
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: install client deps
        working-directory: client
        run: npm install

      - name: run client tests (ci mode)
        working-directory: client
        run: npx vitest run

      - name: build client docker image
        run: docker build -t client-app ./client

      - name: run client container
        run: |
          docker run -d --name client_test -p 5174:5173 client-app
          sleep 5
          docker ps | grep client_test

      - name: stop client container
        run: docker rm -f client_test

  # -----------------------------
  # server: test + docker
  # -----------------------------
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: install server deps
        working-directory: server
        run: npm install

      - name: run server tests (ci mode)
        working-directory: server
        run: npx vitest run

      - name: build server docker image
        run: docker build -t server-app ./server

      - name: run server container
        run: |
          docker run -d --name server_test -p 5001:5000 server-app
          sleep 5
          docker ps | grep server_test

      - name: stop server container
        run: docker rm -f server_test
